### ISSUE TITLE
Rendering glitch when zooming from year to month on timeline

### ISSUE THREAD

**Issue by Rockwell95** [netzwerg/react-svg-timeline#103]
There appears to be an issue with date markers not appearing immediately when zooming in from the year-level view on the timeline to the month-level view. However upon dragging the timeline after being zoomed in, the markers re-appear again.

This issue was first discovered on my organization's own implementation of the timeline in our own React-based web app, but we have been able to reproduce it on the react-svg-timeline demo page as well (see the attached GIF). Is there a potential workaround for this behaviour we can implement on our side in the meantime?

![Peek 2022-11-09 14-32](https://user-images.githubusercontent.com/8961845/200927403-f40fd6b2-e0c8-4adc-b05d-6ca0b8a8bda2.gif)

**Comment by protyze** [comment]
Good catch. Once @netzwerg has reviewed the PR we'll merge it and publish a version with the fix.

**Comment by Rockwell95** [comment]
Thank you for the quick turnaround! We'll keep an eye out for the fix!
