### ISSUE TITLE
Option to use customised tooltips when items are hovered

### ISSUE THREAD

**Issue by kashifshamaz21** [netzwerg/react-svg-timeline#33]
<img width="1398" alt="Screen Shot 2021-02-22 at 6 54 31 PM" src="https://user-images.githubusercontent.com/6056421/108714509-a2398480-753f-11eb-9851-d8cedec45a7e.png">

Hi @netzwerg ,

I would like to integrate this timeline component in my app. I have setup the library locally, and while playing around with the example code, when I tried to increase the content inside the tooltip, it didn't scale well. The content was cut-off.
Looking at the code for `EventTooltip` in `Marks.tsx` , it looks like the height of the tooltip is set to `30` and width is also constant.

```
const EventTooltip = ({ type, y, parentWidth, text, triggerRef }: EventTooltipProps) => {
  const classes = useTooltipStyle()
  const width = type === 'period' ? 180 : 100
  const height = 30
  ...
``` 

In my case, I need to show custom content inside the tooltip, whenever my custom icon items are hovered. Is it possible to accomplish this currently using the library's configuration options?

<img width="452" alt="Screen Shot 2021-02-22 at 7 00 30 PM" src="https://user-images.githubusercontent.com/6056421/108714995-44596c80-7540-11eb-8d6f-e7c7b085a4e6.png">
PS: My tooltip content would have content along those lines. As you can see, the content is quite a bit, and hence to be able to show that, we have to provide a custom tooltip to be used instead of current default.

Thanks for any pointers you can provide on this.

**Comment by netzwerg** [comment]
Hey @kashifshamaz21 – Unfortunately, tooltips cannot be customized yet and width/height values are indeed hard-coded. Coming up with a scalable solution is not trivial, and I don't have the resources at the moment. However, I'd happily accept a PR if you'd like to submit a suggestion which would serve your needs!

**Comment by kashifshamaz21** [comment]
@netzwerg Thank you for the quick response on this. Though I don't have much experience with creating/templating svg elements, i will try to google around a possible solution for keeping width & height of the tooltip as `auto`. Any pointers you have on how should i go about exploring this?

**Comment by netzwerg** [comment]
@kashifshamaz21 Maybe you could start with forking the repo and implementing a solution which works for your very specific requirements. Once this works, we could try to generalize it.

**Comment by kashifshamaz21** [comment]
@netzwerg Thanks, yes I have now forked the repo and trying some options. One issue I'm running into while running the `example` app is, when I make modifications in the lib's source files, and run all following commands, the example app is still getting bundled with older code of the lib.

```
react-svg-timeline kshamaz$   yarn build
react-svg-timeline kshamaz$   cd example && yarn build && yarn start
```

**Note**: 
The code changes i'm making in the src files of the lib, they are getting reflected in the built output files :
```
react-svg-timeline.esm.js
react-svg-timeline.cjs.development.js
```
But the output JS bundle of the example app folder, `example.81dc3a59.97972de1.78f6bbb9.js` is not reflecting my code changes. I tried deleting the `.parcel-cache` folder inside `example` directory, but that also didn't help.

Have you run into such an issue in your testing ? Or is there anything I'm doing incorrectly here? Appreciate any help you can provide me on this painful issue.

**Comment by netzwerg** [comment]
@kashifshamaz21 You should be able to use `yarn start` in both simultaneously (e.g. in two terminal tabs), which should build the lib and run the example continuously.

**Comment by kashifshamaz21** [comment]
@netzwerg I have opened a PR #34 for this as well as some other improvements I felt would make this library even more customisable and cover more cases. Pls review and let me know if we can merge the PR. Thanks for your time.

**Comment by kashifshamaz21** [comment]
@netzwerg I'm closing this issue, as #34 has been merged and released now. Further enhancements for tooltip customisations can be tracked and discussed in new PRs :)
