### ISSUE TITLE
allow for changing of x axis font sizes

### ISSUE THREAD

**Issue by smonero** [netzwerg/react-svg-timeline#71]
I would like to be able to change the font size via xAxisTheme interface of the month and year texts

https://github.com/netzwerg/react-svg-timeline/pull/70

thanks!

**Comment by netzwerg** [comment]
Hey @smonero – Thanks for your patience (I was away for a week). I noticed that you closed your PR, is this still an issue for you?

**Comment by smonero** [comment]
hey :) yeah I reopened it thanks!

**Comment by protyze** [comment]
#70 is merged and published with v0.18.0
