### ISSUE TITLE
Event handler for clicking on event

### ISSUE THREAD

**Issue by cubecleveland** [netzwerg/react-svg-timeline#93]
Sorry, probably not the place for asking, but just need a click handler  for clikcing on each event, is that possible ?

**Comment by netzwerg** [comment]
There's an [onEventClick](https://github.com/netzwerg/react-svg-timeline/blob/bc317f9efbaac5715037f193a93471e1cefee469/src/Timeline.tsx#L42) prop that you can pass in.
