### ISSUE TITLE
Odd warning that does not seem to impact performance

### ISSUE THREAD

**Issue by TD-DO** [netzwerg/react-svg-timeline#95]
When I run my program I get:
WARNING in ./node_modules/ts-deepmerge/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/xxx/node_modules/ts-deepmerge/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/xxx/node_modules/ts-deepmerge/src/index.ts'
Where xxx is the path to my program.

I am on version 0.23.3
It doesn't seem to harm anything but I would like this warning to be suppressed, either by you or if you could give me some way to suppress it myself it would be greatly appreciated

**Comment by netzwerg** [comment]
I don't think that this is related to `react-svg-timeline`, looks more like a `ts-deepmerge` issue. Is your project based on create-react-app? If yes, it could be related to https://github.com/facebook/create-react-app/pull/11752 (comments contain suggestions on how to suppress the warning). Hope this helps!

**Comment by TD-DO** [comment]
This helps so much, thank you!! I really appreciate your speed and helpfulness!
